// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: lines_longer_than_80_chars

part of 'change_status_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChangeStatusResponse _$ChangeStatusResponseFromJson(Map<String, dynamic> json) => ChangeStatusResponse(
      status: json['status'] as String?,
      message: json['message'] as String?,
      data: json['data'] == null ? null : _$DataFromJson(json['data'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$ChangeStatusResponseToJson(ChangeStatusResponse instance) => <String, dynamic>{
      'status': instance.status,
      'message': instance.message,
      'data': _$DataToJson(instance.data!),
    };

Data? _$DataFromJson(Map<String, dynamic>? json) => Data(
      id: json?['id'] as String?,
      status: json?['status'] as String?,
      ticketInfo: json?['ticketInfo'] == null ? null : _$TicketInfoFromJson(json?['ticketInfo'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'id': instance.id,
      'status': instance.status,
      'ticketInfo': _$TicketInfoToJson(instance.ticketInfo!),
    };

TicketInfo _$TicketInfoFromJson(Map<String, dynamic> json) => TicketInfo(
      id: json['id'] as int?,
      barcode: json['barcode'] as String?,
      createDate: json['createDate'] as String?,
      parkingTime: json['parkingTime'] as String?,
      checkoutTime: json['checkoutTime'] as String?,
      payment: json['payment'] as String?,
      voucherMainId: json['voucherMainId'] as int?,
      voucherCodeNo: json['voucherCodeNo'] as String?,
      cashier: json['cashier'] as String?,
      checkoutStatus: json['checkoutStatus'] as String?,
      requestedByUser: json['requestedByUser'] as int?,
      initialCheckinTime: json['initialCheckinTime'] as String?,
      dataCheckinTime: json['dataCheckinTime'] as String?,
      requestedTime: json['requestedTime'] as String?,
      onthewayTime: json['onthewayTime'] as String?,
      paymentCalculatedOn: json['paymentCalculatedOn'] as String?,
      finalCheckoutTime: json['finalCheckoutTime'] as String?,
      parkingLocation: json['parkingLocation'] as int?,
      parkingLocationnew: json['parkingLocationnew'] as String?,
      slotId: json['slotId'] as int?,
      vehicleNumber: json['vehicleNumber'] as String?,
      vehicleModel: json['vehicleModel'] as int?,
      vehicleColr: json['vehicleColr'] as int?,
      emirates: json['emirates'] as int?,
      cvaIn: json['cvaIn'] as int?,
      cvaOut: json['cvaOut'] as int?,
      guestType: json['guestType'] as int?,
      slot: json['slot'] as String?,
      customerDetails: json['customerDetails'] as String?,
      customerMobile: json['customerMobile'] as String?,
      vehicleRemark: json['vehicleRemark'] as String?,
      userId: json['userId'] as int?,
      userType: json['userType'] as String?,
      status: json['status'] as String?,
      inBy: json['inBy'] as int?,
      outBy: json['outBy'] as int?,
      paymentMethod: json['paymentMethod'] as int?,
      paymentNote: json['paymentNote'] as String?,
      grossAmount: json['grossAmount'] as String?,
      discountAmount: json['discountAmount'] as String?,
      voucherBarcode: json['voucherBarcode'] as String?,
      vatPercentage: json['vatPercentage'] as String?,
      vatAmount: json['vatAmount'] as String?,
      subTotal: json['subTotal'] as String?,
      outletOfferId: json['outletOfferId'] as String?,
      offerTotalMidnight: json['offerTotalMidnight'] as String?,
      paymentPaidMethod: json['paymentPaidMethod'] as String?,
      modifiedOn: json['modifiedOn'] as String?,
      modifiedBy: json['modifiedBy'] as int?,
      modifiedByUser: json['modifiedByUser'] as String?,
      paidOnCheckin: json['paidOnCheckin'] as String?,
      customerRequest: json['customerRequest'] as String?,
      customerEmail: json['customerEmail'] as String?,
      customerPhoneNo: json['customerPhoneNo'] as String?,
      carColorName: json['carColorName'] as String?,
      carModelName: json['carModelName'] as String?,
      locationName: json['locationName'] as String?,
      cvaInName: json['cvaInName'] as String?,
      cvaOutName: json['cvaOutName'] as String?,
      userName: json['userName'] as String?,
      guestTypeName: json['guestTypeName'] as String?,
      emiratesName: json['emiratesName'] as String?,
    );

Map<String, dynamic> _$TicketInfoToJson(TicketInfo instance) => <String, dynamic>{
      'id': instance.id,
      'barcode': instance.barcode,
      'createDate': instance.createDate,
      'parkingTime': instance.parkingTime,
      'checkoutTime': instance.checkoutTime,
      'payment': instance.payment,
      'voucherMainId': instance.voucherMainId,
      'voucherCodeNo': instance.voucherCodeNo,
      'cashier': instance.cashier,
      'checkoutStatus': instance.checkoutStatus,
      'requestedByUser': instance.requestedByUser,
      'initialCheckinTime': instance.initialCheckinTime,
      'dataCheckinTime': instance.dataCheckinTime,
      'requestedTime': instance.requestedTime,
      'onthewayTime': instance.onthewayTime,
      'paymentCalculatedOn': instance.paymentCalculatedOn,
      'finalCheckoutTime': instance.finalCheckoutTime,
      'parkingLocation': instance.parkingLocation,
      'parkingLocationnew': instance.parkingLocationnew,
      'slotId': instance.slotId,
      'vehicleNumber': instance.vehicleNumber,
      'vehicleModel': instance.vehicleModel,
      'vehicleColr': instance.vehicleColr,
      'emirates': instance.emirates,
      'cvaIn': instance.cvaIn,
      'cvaOut': instance.cvaOut,
      'guestType': instance.guestType,
      'slot': instance.slot,
      'customerDetails': instance.customerDetails,
      'customerMobile': instance.customerMobile,
      'vehicleRemark': instance.vehicleRemark,
      'userId': instance.userId,
      'userType': instance.userType,
      'status': instance.status,
      'inBy': instance.inBy,
      'outBy': instance.outBy,
      'paymentMethod': instance.paymentMethod,
      'paymentNote': instance.paymentNote,
      'grossAmount': instance.grossAmount,
      'discountAmount': instance.discountAmount,
      'voucherBarcode': instance.voucherBarcode,
      'vatPercentage': instance.vatPercentage,
      'vatAmount': instance.vatAmount,
      'subTotal': instance.subTotal,
      'outletOfferId': instance.outletOfferId,
      'offerTotalMidnight': instance.offerTotalMidnight,
      'paymentPaidMethod': instance.paymentPaidMethod,
      'modifiedOn': instance.modifiedOn,
      'modifiedBy': instance.modifiedBy,
      'modifiedByUser': instance.modifiedByUser,
      'paidOnCheckin': instance.paidOnCheckin,
      'customerRequest': instance.customerRequest,
      'customerEmail': instance.customerEmail,
      'customerPhoneNo': instance.customerPhoneNo,
      'carColorName': instance.carColorName,
      'carModelName': instance.carModelName,
      'locationName': instance.locationName,
      'cvaInName': instance.cvaInName,
      'cvaOutName': instance.cvaOutName,
      'userName': instance.userName,
      'guestTypeName': instance.guestTypeName,
      'emiratesName': instance.emiratesName,
    };
