// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: lines_longer_than_80_chars

part of 'image_upload_form_response_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ImageUploadFormResponseModel _$ImageUploadFormResponseModelFromJson(Map<String, dynamic> json) => ImageUploadFormResponseModel(
      status: json['status'] as String?,
      message: json['message'] as String?,
      allowedImagesPerVehicle: json['allowed_images_per_vehicle'] as int?,
      data:json['data'] == null ? null :  _$DataFromJson(json['data'] as Map<String, dynamic>),
    );

// Map<String, dynamic> _$ImageUploadFormResponseModelToJson(ImageUploadFormResponseModel instance) => <String, dynamic>{
//       'status': instance.status,
//       'message': instance.message,
//       'allowed_images_per_vehicle': instance.allowedImagesPerVehicle,
//       'data': _$DataToJson(instance.data),
//     };

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      ticketInfo: json['ticket_info'] == null ? null : _$TicketInfoFromJson(json['ticket_info'] as Map<String, dynamic>),
      vehicleImages: json['vehicle_images'] == null ? null : (json['vehicle_images'] as List<dynamic>).map((e) => _$VehicleImagesFromJson(e as Map<String, dynamic>)).toList(),
      vehicleParts:json['vehicle_parts'] == null ? null : (json['vehicle_parts'] as List<dynamic>).map((e) => _$VehiclePartsFromJson(e as Map<String, dynamic>)).toList(),
    );

// Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
//       'ticket_info': _$TicketInfoToJson(instance.ticketInfo),
//       'vehicle_images': instance.vehicleImages?.map(_$VehicleImagesToJson) ?? [],
//       'vehicle_parts': instance.vehicleParts?.map(_$VehiclePartsToJson) ?? [],
//     };

TicketInfo _$TicketInfoFromJson(Map<String, dynamic> json) => TicketInfo(
      id: json['id'] as int?,
      barcode: json['barcode'] as String?,
      createDate: json['create_date'] as String?,
      parkingTime: json['parking_time'] as String?,
      checkoutTime: json['checkout_time'] as String?,
      payment: json['payment'] as String?,
      voucherMainId: json['voucher_main_id'] as int?,
      voucherCodeNo: json['voucher_code_no'] as String?,
      cashier: json['cashier'] as String?,
      checkoutStatus: json['checkout_status'] as String?,
      requestedByUser: json['requested_by_user'] as int?,
      initialCheckinTime: json['initial_checkin_time'] as String?,
      dataCheckinTime: json['data_checkin_time'] as String?,
      requestedTime: json['requested_time'] as String?,
      onthewayTime: json['ontheway_time'] as String?,
      paymentCalculatedOn: json['payment_calculated_on'] as String?,
      finalCheckoutTime: json['final_checkout_time'] as String?,
      parkingLocation: json['parking_location'] as int?,
      parkingLocationnew: json['parking_locationnew'] as String?,
      slotId: json['slot_id'] as int?,
      vehicleNumber: json['vehicle_number'] as String?,
      vehicleModel: json['vehicle_model'] as int?,
      vehicleColr: json['vehicle_colr'] as int?,
      emirates: json['emirates'] as int?,
      cvaIn: json['cva_in'] as int?,
      cvaOut: json['cva_out'] as int?,
      guestType: json['guest_type'] as int?,
      slot: json['slot'] as String?,
      customerDetails: json['customer_details'] as String?,
      customerMobile: json['customer_mobile'] as String?,
      vehicleRemark: json['vehicle_remark'] as String?,
      userId: json['user_id'] as int?,
      userType: json['user_type'] as String?,
      status: json['status'] as String?,
      inBy: json['in_by'] as int?,
      outBy: json['out_by'] as int?,
      paymentMethod: json['payment_method'] as int?,
      paymentNote: json['payment_note'] as String?,
      grossAmount: json['gross_amount'] as String?,
      discountAmount: json['discount_amount'] as String?,
      voucherBarcode: json['voucher_barcode'] as String?,
      vatPercentage: (json['vat_percentage'] as num?)?.toDouble(),
      vatAmount: (json['vat_amount'] as num?)?.toDouble(),
      subTotal: (json['sub_total'] as num?)?.toDouble(),
      outletOfferId: json['outlet_offer_id'] as String?,
      offerTotalMidnight: json['payment_paid_method'] as String?,
      paymentPaidMethod: json['paymentPaidMethod'] as String?,
      modifiedOn: json['modified_on'] as String?,
      modifiedBy: json['modified_by'] as int?,
      modifiedByUser: json['modified_by_user'] as String?,
      paidOnCheckin: json['paid_on_checkin'] as String?,
      customerRequest: json['customer_request'] as String?,
      customerEmail: json['customer_email'] as String?,
      customerPhoneNo: json['customer_phone_no'] as String?,
      carColorName: json['car_color_name'] as String?,
      carModelName: json['car_model_name'] as String?,
      locationName: json['location_name'] as String?,
      cvaInName: json['cva_in_name'] as String?,
      cvaOutName: json['cva_out_name'] as String?,
      userName: json['user_name'] as String?,
      guestTypeName: json['guest_type_name'] as String?,
      emiratesName: json['emirates_name'] as String?,
    );

// Map<String, dynamic> _$TicketInfoToJson(TicketInfo instance) => <String, dynamic>{
//       'id': instance.id,
//       'barcode': instance.barcode,
//       'createDate': instance.createDate,
//       'parkingTime': instance.parkingTime,
//       'checkoutTime': instance.checkoutTime,
//       'payment': instance.payment,
//       'voucherMainId': instance.voucherMainId,
//       'voucherCodeNo': instance.voucherCodeNo,
//       'cashier': instance.cashier,
//       'checkoutStatus': instance.checkoutStatus,
//       'requestedByUser': instance.requestedByUser,
//       'initialCheckinT?ime': instance.initialCheckinTime,
//       'dataCheckinT?ime': instance.dataCheckinTime,
//       'requestedTime': instance.requestedTime,
//       'onthewayTime': instance.onthewayTime,
//       'paymentCalculatedOn': instance.paymentCalculatedOn,
//       'finalCheckoutTime': instance.finalCheckoutTime,
//       'parkingLocation': instance.parkingLocation,
//       'parkingLocationnew': instance.parkingLocationnew,
//       'slotId': instance.slotId,
//       'vehicleNumber': instance.vehicleNumber,
//       'vehicleModel': instance.vehicleModel,
//       'vehicleColr': instance.vehicleColr,
//       'emirates': instance.emirates,
//       'cvaIn': instance.cvaIn,
//       'cvaOut': instance.cvaOut,
//       'guestType': instance.guestType,
//       'slot': instance.slot,
//       'customerDetails': instance.customerDetails,
//       'customerMobile': instance.customerMobile,
//       'vehicleRemark': instance.vehicleRemark,
//       'userId': instance.userId,
//       'userType': instance.userType,
//       'status': instance.status,
//       'inBy': instance.inBy,
//       'outBy': instance.outBy,
//       'paymentMethod': instance.paymentMethod,
//       'paymentNote': instance.paymentNote,
//       'grossAmount': instance.grossAmount,
//       'discountAmount': instance.discountAmount,
//       'voucherBarcode': instance.voucherBarcode,
//       'vatPercentage': instance.vatPercentage,
//       'vatAmount': instance.vatAmount,
//       'subTotal': instance.subTotal,
//       'outletOfferId': instance.outletOfferId,
//       'offerTotalMidnight': instance.offerTotalMidnight,
//       'paymentPaidMethod': instance.paymentPaidMethod,
//       'modifiedOn': instance.modifiedOn,
//       'modifiedBy': instance.modifiedBy,
//       'modifiedByUser': instance.modifiedByUser,
//       'paidOnCheckin': instance.paidOnCheckin,
//       'customerRequest': instance.customerRequest,
//       'customerEmail': instance.customerEmail,
//       'customerPhoneNo': instance.customerPhoneNo,
//       'carColorName': instance.carColorName,
//       'carModelName': instance.carModelName,
//       'locationName': instance.locationName,
//       'cvaInName': instance.cvaInName,
//       'cvaOutName': instance.cvaOutName,
//       'userName': instance.userName,
//       'guestTypeName': instance.guestTypeName,
//       'emiratesName': instance.emiratesName,
//     };

VehicleImages _$VehicleImagesFromJson(Map<String, dynamic> json) => VehicleImages(
      imageId: json['image_id'] as int?,
      parkingEntryId: json['parking_entry_id'] as int?,
      vehiclePartId: json['vehicle_part_id'] as int?,
      vehicleCategoryId: json['vehicle_category_id'] as int?,
      imagePath: json['image_path'] as String?,
      remark: json['remark'] as String?,
      addedBy: json['added_by'] as int?,
      addedOn: json['added_on'] as String?,
      status: json['status'] as String?,
      partId: json['part_id'] as int?,
      partTitle: json['part_title'] as String?,
      partPosition: json['part_position'] as String?,
      partStatus: json['part_status'] as String?,
    );

// Map<String, dynamic> _$VehicleImagesToJson(VehicleImages instance) => <String, dynamic>{
//       'image_id': instance.imageId,
//       'parking_entry_id': instance.parkingEntryId,
//       'vehicle_part_id': instance.vehiclePartId,
//       'vehicle_category_id': instance.vehicleCategoryId,
//       'image_path': instance.imagePath,
//       'remark': instance.remark,
//       'added_by': instance.addedBy,
//       'added_on': instance.addedOn,
//       'status': instance.status,
//       'part_id': instance.partId,
//       'part_title': instance.partTitle,
//       'part_position': instance.partPosition,
//       'part_status': instance.partStatus,
//     };

VehicleParts _$VehiclePartsFromJson(Map<String, dynamic> json) => VehicleParts(
      partId: json['part_id'] as int?,
      vehicleCategoryId: json['vehicle_category_id'] as int?,
      partTitle: json['part_title'] as String?,
      remark: json['remark'] as String?,
      partPosition: json['part_position'] as String?,
      partStatus: json['part_status'] as String?,
    );

// Map<String, dynamic> _$VehiclePartsToJson(VehicleParts instance) => <String, dynamic>{
//       'part_id': instance.partId,
//       'vehicle_category_id': instance.vehicleCategoryId,
//       'part_title': instance.partTitle,
//       'remark': instance.remark,
//       'part_position': instance.partPosition,
//       'part_status': instance.partStatus,
//     };
